// src/components/features/Svelte/performance04/_children/Child10.svelte
<script lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart, recordFinished, logProps } from "@/_global/lib/performance04";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import type { RelayProps } from "../_models/RelayContext.svelte";

	const { relay }: RelayProps = $props();

	const relayData = $derived.by(() => {
		if (!relay) return 0;

		logProps();

		return relay;
	});

	const { svelteRaceId, svelteSetRaceId } = useStore('svelteRaceId');
	const { setRelayDataWithLog } = useRelayDataContexts();

	$effect(() => {
		if (svelteRaceId() !== 'Props' || !relayData) return;

		recordFinished('Props');

		svelteSetRaceId('Context');
		recordStart('Context');
		setRelayDataWithLog(1);
	});
</script>

// src/components/features/Solid/performance04/_children/Child10.tsx
import { createEffect, createMemo } from "solid-js";
import { useStore } from "@/_global/piquo";
import { recordStart, recordFinished, logProps } from "@/_global/lib/performance04";
import { useRelayDataContexts } from "../_models/relayContext";
import type { RelayProps } from "../_models/relayContext";

export default function Child10(props: RelayProps) {
	const { solidRaceId, solidSetRaceId } = useStore('solidRaceId');
	const { setRelayDataWithLog } = useRelayDataContexts();

	const relayData = createMemo(() => {
		if (!props.relay) return 0;

		logProps();
		return props.relay;
	});

	createEffect(() => {
		if (solidRaceId() !== 'Props' || !relayData()) return;

		recordFinished('Props');

		solidSetRaceId('Context');
		recordStart('Context');
		setRelayDataWithLog(1);
	});

	return null;
};
