// src/components/features/Svelte/performance03/_quantumStores/Quantum10.svelte
<script lang="ts">
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { svelteSetQuantumStoreStart, svelteSetQuantum01, svelteQuantum10 } = useStore('svelteQuantum');

	const incrementStore = (value: number) => {
		svelteSetQuantum01(value + 1);
	};

	$effect(() => {
		if (!svelteQuantum10()) return;

		if (svelteQuantum10() >= loopTotal) {
			recordFinished('QuantumStore');

			svelteSetQuantumStoreStart(0);
			return;
		}

		incrementStore(svelteQuantum10());
	});
</script>

// src/components/features/Solid/performance03/_quantumStores/Quantum10.tsx
import { createEffect } from "solid-js";
import { loopTotal, recordFinished } from "@/_global/lib/performance03";
import { useStore } from "@/_global/piquo";

export default function Quantum10() {
	const { solidSetQuantumStoreStart, solidSetQuantum01, solidQuantum10 } = useStore('solidQuantum');

	const incrementStore = (value: number) => {
		solidSetQuantum01(value + 1);
	};

	createEffect(() => {
		if (!solidQuantum10()) return;

		if (solidQuantum10() >= loopTotal) {
			recordFinished('QuantumStore');

			solidSetQuantumStoreStart(0);
			return;
		}

		incrementStore(solidQuantum10());
	});

	return null;
}
