// src/components/features/Svelte/performance03/_quantumStores/Quantum10.svelte
<script lang="ts">
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { svelteSetQuantumStoreStart, svelteSetQuantum01, svelteQuantum10 } = useStore('svelteQuantum');

	const incrementStore = (value: number) => {
		svelteSetQuantum01(value + 1);
	};

	$effect(() => {
		if (!svelteQuantum10()) return;

		if (svelteQuantum10() >= loopTotal) {
			recordFinished('QuantumStore');

			svelteSetQuantumStoreStart(0);
			return;
		}

		incrementStore(svelteQuantum10());
	});
</script>

// src/components/features/Vue/performance03/_quantumStores/Quantum10.vue
<script setup lang="ts">
	import { watch } from "vue";
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { vueSetQuantumStoreStart, vueSetQuantum01, vueQuantum10 } = useStore('vueQuantum');

	const incrementStore = (value: number) => {
		vueSetQuantum01(value + 1);
	};

	watch(
		() => vueQuantum10(),
		() => {
			if (!vueQuantum10()) return;

			if (vueQuantum10() >= loopTotal) {
				recordFinished('QuantumStore');

				vueSetQuantumStoreStart(0);
				return;
			}

			incrementStore(vueQuantum10());
		},
		{ immediate: true }
	);
</script>
<template>
	<!-- return null -->
</template>
