// src/components/features/React/performance04/_quantumStores/Quantum00.tsx
/** @jsxImportSource react */

import { useLayoutEffect, useRef, useSyncExternalStore } from "react";
import { recordStart } from "@/_global/lib/performance04";
import { useStore } from "../_models/stores";

export default function Quantum00() {
	const raceId = useStore('raceId');
	const quantum01 = useStore('quantum01');
	const raceIdStore = useSyncExternalStore(raceId.subscribe, raceId.getSnapshot, raceId.getServerSnapshot);

	const num = useRef(0);

	useLayoutEffect(() => {
		if (raceIdStore !== 'Store') return;

		recordStart('Store');
		quantum01.setStore(num.current + 1);
		num.current++;
	}, [ raceIdStore ]);

	return null;
}

// src/components/features/Solid/performance04/_quantumStores/Quantum00.tsx
import { createEffect } from "solid-js";
import { useStore } from "@/_global/piquo";
import { recordStart } from "@/_global/lib/performance04";

export default function Quantum00() {
	const { solidRaceId } = useStore('solidRaceId');
	const { solidSetQuantum01 } = useStore('solidQuantum');

	let num = 0;

	createEffect(() => {
		if (solidRaceId() !== 'Store') return;

		recordStart('Store');
		solidSetQuantum01(num + 1);
		num++;
	});

	return null;
}
