// src/components/features/Svelte/performance04/_quantumStores/Quantum10.svelte
<script lang="ts">
	import { recordFinished, logStore } from "@/_global/lib/performance04";
	import { useStore } from "@/_global/piquo";

	const { svelteQuantum10 } = useStore('svelteQuantum');
	const { svelteSetRaceId } = useStore('svelteRaceId');

	const relayData = $derived.by(() => {
		if (!svelteQuantum10()) return 0;

		logStore();

		return svelteQuantum10();
	});

	$effect(() => {
		if (!relayData) return;

		recordFinished('Store');
		recordFinished('Race');
		svelteSetRaceId(null);
	});
</script>

// src/components/features/Solid/performance04/_quantumStores/Quantum10.tsx
import { createEffect, createMemo } from "solid-js";
import { recordFinished, logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum10() {
	const { solidQuantum10 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum10()) return 0;

		logStore();
		return solidQuantum10();
	});

	createEffect(() => {
		if (!relayData()) return;

		recordFinished('Store');
		recordFinished('Race');
	});

	return null;
}
