// src/components/features/Vue/performance04/_quantumStores/Quantum10.vue
<script setup lang="ts">
	import { computed, watch } from "vue";
	import { recordFinished, logStore } from "@/_global/lib/performance04";
	import { useStore } from "@/_global/piquo";

	const { vueQuantum10 } = useStore('vueQuantum');
	const { vueSetRaceId } = useStore('vueRaceId');

	const relayData = computed(() => {
		if (!vueQuantum10()) return 0;

		logStore();

		return vueQuantum10();
	});

	watch(
		() => relayData.value,
		() => {
			if (!relayData.value) return;

			recordFinished('Store');
			recordFinished('Race');
			vueSetRaceId(null);
		}
	);
</script>
<template>
	<!-- return null -->
</template>

// src/components/features/Solid/performance04/_quantumStores/Quantum10.tsx
import { createEffect, createMemo } from "solid-js";
import { recordFinished, logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum10() {
	const { solidQuantum10 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum10()) return 0;

		logStore();
		return solidQuantum10();
	});

	createEffect(() => {
		if (!relayData()) return;

		recordFinished('Store');
		recordFinished('Race');
	});

	return null;
}
