// src/components/features/React/performance04/_quantumStores/Quantum04.tsx
/** @jsxImportSource react */

import { useLayoutEffect, useMemo, useSyncExternalStore } from "react";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "../_models/stores";

export default function Quantum04() {
	const quantum04 = useStore('quantum04');
	const quantum05 = useStore('quantum05');
	const quantumStore = useSyncExternalStore(quantum04.subscribe, quantum04.getSnapshot, quantum04.getServerSnapshot);

	const relayData = useMemo(() => {
		if (!quantumStore) return 0;

		logStore();
		return quantumStore;
	}, [ quantumStore ]);

	useLayoutEffect(() => {
		if (!relayData) return;

		quantum05.setStore(relayData);
	}, [ relayData ]);

	return null;
}

// src/components/features/Solid/performance04/_quantumStores/Quantum04.tsx
import { createEffect, createMemo } from "solid-js";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum04() {
	const { solidQuantum04, solidSetQuantum05 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum04()) return 0;

		logStore();
		return solidQuantum04();
	});

	createEffect(() => {
		if (!relayData()) return;

		solidSetQuantum05(relayData());
	});

	return null;
}
