// src/components/features/React/performance04/_quantumStores/Quantum06.tsx
/** @jsxImportSource react */

import { useLayoutEffect, useMemo, useSyncExternalStore } from "react";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "../_models/stores";

export default function Quantum06() {
	const quantum06 = useStore('quantum06');
	const quantum07 = useStore('quantum07');
	const quantumStore = useSyncExternalStore(quantum06.subscribe, quantum06.getSnapshot, quantum06.getServerSnapshot);

	const relayData = useMemo(() => {
		if (!quantumStore) return 0;

		logStore();
		return quantumStore;
	}, [ quantumStore ]);

	useLayoutEffect(() => {
		if (!relayData) return;

		quantum07.setStore(relayData);
	}, [ relayData ]);

	return null;
}

// src/components/features/Solid/performance04/_quantumStores/Quantum06.tsx
import { createEffect, createMemo } from "solid-js";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum06() {
	const { solidQuantum06, solidSetQuantum07 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum06()) return 0;

		logStore();
		return solidQuantum06();
	});

	createEffect(() => {
		if (!relayData()) return;

		solidSetQuantum07(relayData());
	});

	return null;
}
