// src/components/features/React/performance03/_quantumContexts/Quantum03.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum03() {
	const { quantumData03, setQuantumData04 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData03) return;

		setQuantumData04(quantumData03);
	}, [ quantumData03 ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum03.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum03() {
	const { quantumData03, setQuantumData04 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData03()) return;

		setQuantumData04(quantumData03());
	});

	return null;
}
