// src/components/features/React/performance03/_quantumContexts/Quantum05.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum05() {
	const { quantumData05, setQuantumData06 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData05) return;

		setQuantumData06(quantumData05);
	}, [ quantumData05 ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum05.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum05() {
	const { quantumData05, setQuantumData06 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData05()) return;

		setQuantumData06(quantumData05());
	});

	return null;
}
