// src/components/features/React/performance03/_quantumContexts/Quantum07.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum07() {
	const { quantumData07, setQuantumData08 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData07) return;

		setQuantumData08(quantumData07);
	}, [ quantumData07 ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum07.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum07() {
	const { quantumData07, setQuantumData08 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData07()) return;

		setQuantumData08(quantumData07());
	});

	return null;
}
