// src/components/features/React/performance03/_quantumContexts/Quantum02.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum02() {
	const { quantumData02, setQuantumData03 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData02) return;

		setQuantumData03(quantumData02);
	}, [ quantumData02 ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum02.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum02() {
	const { quantumData02, setQuantumData03 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData02()) return;

		setQuantumData03(quantumData02());
	});

	return null;
}
