// src/components/features/Svelte/performance03/_quantumContexts/Quantum10.svelte
<script lang="ts">
	import { useQuantumDataContexts } from "../_models/QuantumContext.svelte";
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { svelteSetQuantumContextStart } = useStore('svelteQuantum');
	const { setQuantumData01, quantumData10 } = useQuantumDataContexts();

	const incrementContext = (value: number) => {
		setQuantumData01(value + 1);
	};

	$effect(() => {
		if (!quantumData10()) return;

		if (quantumData10() >= loopTotal) {
			recordFinished('QuantumContext');

			svelteSetQuantumContextStart(0);
			return;
		}

		incrementContext(quantumData10());
	});
</script>

// src/components/features/Solid/performance03/_quantumContexts/Quantum10.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";
import { loopTotal, recordFinished } from "@/_global/lib/performance03";
import { useStore } from "@/_global/piquo";

export default function Quantum10() {
	const { solidSetQuantumContextStart } = useStore('solidQuantum');
	const { setQuantumData01, quantumData10 } = useQuantumDataContexts();

	const incrementContext = (value: number) => {
		setQuantumData01(value + 1);
	};

	createEffect(() => {
		if (!quantumData10()) return;

		if (quantumData10() >= loopTotal) {
			recordFinished('QuantumContext');

			solidSetQuantumContextStart(0);
			return;
		}

		incrementContext(quantumData10());
	});

	return null;
}
