// src/components/features/React/performance03/_quantumContexts/Quantum09.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum09() {
	const { quantumData09, setQuantumData10 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData09) return;

		setQuantumData10(quantumData09);
	}, [ quantumData09 ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum09.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum09() {
	const { quantumData09, setQuantumData10 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData09()) return;

		setQuantumData10(quantumData09());
	});

	return null;
}
