// src/components/features/React/performance03/_quantumContexts/Quantum00.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect, useSyncExternalStore } from "react";
import { QuantumContext } from "../_models/quantumContext";
import { recordStart } from "@/_global/lib/performance03";
import { useStore } from "../_models/stores";

export default function Quantum00() {
	const contextStart = useStore('contextStart');
	const store = useSyncExternalStore(contextStart.subscribe, contextStart.getSnapshot, contextStart.getServerSnapshot);
	const { setQuantumData01 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!store) return;

		recordStart('QuantumContext');
		setQuantumData01(store);
	}, [ store ]);

	return null;
}

// src/components/features/Solid/performance03/_quantumContexts/Quantum00.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";
import { useStore } from "@/_global/piquo";
import { recordStart } from "@/_global/lib/performance03";

export default function Quantum00() {
	const { solidQuantumContextStart } = useStore('solidQuantum');
	const { setQuantumData01 } = useQuantumDataContexts();

	createEffect(() => {
		if (!solidQuantumContextStart()) return;

		recordStart('QuantumContext');
		setQuantumData01(solidQuantumContextStart());
	});

	return null;
}
