// src/components/features/Solid/performance03/_quantumContexts/Quantum04.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum04() {
	const { quantumData04, setQuantumData05 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData04()) return;

		setQuantumData05(quantumData04());
	});

	return null;
}

// src/components/features/React/performance03/_quantumContexts/Quantum04.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum04() {
	const { quantumData04, setQuantumData05 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData04) return;

		setQuantumData05(quantumData04);
	}, [ quantumData04 ]);

	return null;
}
