// src/components/features/Solid/performance03/_quantumContexts/Quantum08.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum08() {
	const { quantumData08, setQuantumData09 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData08()) return;

		setQuantumData09(quantumData08());
	});

	return null;
}

// src/components/features/React/performance03/_quantumContexts/Quantum08.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum08() {
	const { quantumData08, setQuantumData09 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData08) return;

		setQuantumData09(quantumData08);
	}, [ quantumData08 ]);

	return null;
}
