// src/components/features/Solid/performance03/_quantumContexts/Quantum01.tsx
import { createEffect } from "solid-js";
import { useQuantumDataContexts } from "../_models/quantumContext";

export default function Quantum01() {
	const { quantumData01, setQuantumData02 } = useQuantumDataContexts();

	createEffect(() => {
		if (!quantumData01()) return;

		setQuantumData02(quantumData01());
	});

	return null;
}

// src/components/features/React/performance03/_quantumContexts/Quantum01.tsx
/** @jsxImportSource react */

import { useContext, useLayoutEffect } from "react";
import { QuantumContext } from "../_models/quantumContext";

export default function Quantum01() {
	const { quantumData01, setQuantumData02 } = useContext(QuantumContext);

	useLayoutEffect(() => {
		if (!quantumData01) return;

		setQuantumData02(quantumData01);
	}, [ quantumData01 ]);

	return null;
}
