// src/components/features/React/dragRace/nano/string/String05.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoString05() {
	const { $stringStore05 } = useReactStore('nanoString05');
	const store05 = useStore($stringStore05, { ssr: 'initial' });
	const { $stringStore06 } = useReactStore('nanoString06');

	useLayoutEffect(() => {
		const value = +store05;
		if (!value) return;

		$stringStore05.set((value + 1).toString());
		if (value === dragRaceMax) {
			$stringStore05.set('');
			$stringStore06.set('1');
		}
	}, [ store05 ]);

	return null;
}

// src/components/features/Solid/dragRace/nano/string/String05.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoString05() {
	const { stringStore05 } = useNanoStore('nanoString05');
	const store = useStore(stringStore05);
	const { stringStore06 } = useNanoStore('nanoString06');

	createEffect(() => {
		const value = +store();
		if (!value) return;

		stringStore05.set((value + 1).toString());
		if (value === dragRaceMax) {
			stringStore05.set('');
			stringStore06.set('1');
		}
	});

	return null;
}
