// src/components/features/Solid/dragRace/nano/string/String10.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax, recordFinished, logTotal } from "@/_global/lib/dragRace";

export default function NanoString10() {
	const { stringStore10 } = useNanoStore('nanoString10');
	const store = useStore(stringStore10);
	const { startStore } = useNanoStore('nanoStart');

	createEffect(() => {
		const value = +store();
		if (!value) return;

		if (value === dragRaceMax) {
			recordFinished('SolidNanoString');
			logTotal('SolidNano');
			startStore.set(null);
			stringStore10.set('');
		} else {
			stringStore10.set((value + 1).toString());
		}
	});

	return null;
}

// src/components/features/React/dragRace/nano/string/String10.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax, recordFinished, logTotal } from "@/_global/lib/dragRace";

export default function NanoString10() {
	const { $stringStore10 } = useReactStore('nanoString10');
	const store10 = useStore($stringStore10, { ssr: 'initial' });
	const { $startStore } = useReactStore('nanoStart');

	useLayoutEffect(() => {
		const value = +store10;
		if (!value) return;

		if (value === dragRaceMax) {
			recordFinished('ReactNanoString');
			logTotal('ReactNano');
			$startStore.set(null);
			$stringStore10.set('');
		} else {
			$stringStore10.set((value + 1).toString());
		}
	}, [ store10 ]);

	return null;
}
