// src/components/features/Solid/dragRace/nano/number/Number04.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber04() {
	const { numberStore04 } = useNanoStore('nanoNumber04');
	const store = useStore(numberStore04);
	const { numberStore05 } = useNanoStore('nanoNumber05');

	createEffect(() => {
		if (!store()) return;

		numberStore04.set(store() + 1);
		if (store() === dragRaceMax) {
			numberStore04.set(0);
			numberStore05.set(1);
		}
	});

	return null;
}

// src/components/features/React/dragRace/nano/number/Number04.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber04() {
	const { $numberStore04 } = useReactStore('nanoNumber04');
	const store04 = useStore($numberStore04, { ssr: 'initial' });
	const { $numberStore05 } = useReactStore('nanoNumber05');

	useLayoutEffect(() => {
		if (!store04) return;

		$numberStore04.set(store04 + 1);
		if (store04 === dragRaceMax) {
			$numberStore04.set(0);
			$numberStore05.set(1);
		}
	}, [ store04 ]);

	return null;
}
