// src/components/features/Solid/dragRace/nano/number/Number05.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber05() {
	const { numberStore05 } = useNanoStore('nanoNumber05');
	const store = useStore(numberStore05);
	const { numberStore06 } = useNanoStore('nanoNumber06');

	createEffect(() => {
		if (!store()) return;

		numberStore05.set(store() + 1);
		if (store() === dragRaceMax) {
			numberStore05.set(0);
			numberStore06.set(1);
		}
	});

	return null;
}

// src/components/features/React/dragRace/nano/number/Number05.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber05() {
	const { $numberStore05 } = useReactStore('nanoNumber05');
	const store05 = useStore($numberStore05, { ssr: 'initial' });
	const { $numberStore06 } = useReactStore('nanoNumber06');

	useLayoutEffect(() => {
		if (!store05) return;

		$numberStore05.set(store05 + 1);
		if (store05 === dragRaceMax) {
			$numberStore05.set(0);
			$numberStore06.set(1);
		}
	}, [ store05 ]);

	return null;
}
