// src/components/features/Solid/dragRace/nano/number/Number07.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber07() {
	const { numberStore07 } = useNanoStore('nanoNumber07');
	const store = useStore(numberStore07);
	const { numberStore08 } = useNanoStore('nanoNumber08');

	createEffect(() => {
		if (!store()) return;

		numberStore07.set(store() + 1);
		if (store() === dragRaceMax) {
			numberStore07.set(0);
			numberStore08.set(1);
		}
	});

	return null;
}

// src/components/features/React/dragRace/nano/number/Number07.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber07() {
	const { $numberStore07 } = useReactStore('nanoNumber07');
	const store07 = useStore($numberStore07, { ssr: 'initial' });
	const { $numberStore08 } = useReactStore('nanoNumber08');

	useLayoutEffect(() => {
		if (!store07) return;

		$numberStore07.set(store07 + 1);
		if (store07 === dragRaceMax) {
			$numberStore07.set(0);
			$numberStore08.set(1);
		}
	}, [ store07 ]);

	return null;
}
