// src/components/features/Vue/dragRace/nano/number/Number10.vue
<script setup lang="ts">
	import { watch } from "vue";
	import { useStore } from "@nanostores/vue";
	import { useNanoStore } from "../../_models/nano";
	import { dragRaceMax, recordFinished } from "@/_global/lib/dragRace";

	const { $numberStore10 } = useNanoStore('nanoNumber10');
	const store = useStore($numberStore10);
	const { $startStore } = useNanoStore('nanoStart');

	watch(
		() => store.value,
		() => {
			if (!store.value) return;

			if (store.value === dragRaceMax) {
				recordFinished('VueNanoNumber');
				$numberStore10.set(0);
				$startStore.set('string');
			} else {
				$numberStore10.set(store.value + 1);
			}
		},
		{ flush: 'pre' }
	);
</script>
<template>
	<!-- return null -->
</template>

// src/components/features/Solid/dragRace/nano/number/Number10.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax, recordFinished } from "@/_global/lib/dragRace";

export default function NanoNumber10() {
	const { numberStore10 } = useNanoStore('nanoNumber10');
	const store = useStore(numberStore10);
	const { startStore } = useNanoStore('nanoStart');

	createEffect(() => {
		if (!store()) return;

		if (store() === dragRaceMax) {
			recordFinished('SolidNanoNumber');
			numberStore10.set(0);
			startStore.set('string');
		} else {
			numberStore10.set(store() + 1);
		}
	});

	return null;
}
