// src/components/features/React/dragRace/nano/number/Number09.tsx
/** @jsxImportSource react */

import { useLayoutEffect } from "react";
import { useStore } from "@nanostores/react";
import { useReactStore } from "../../_models/stores";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber09() {
	const { $numberStore09 } = useReactStore('nanoNumber09');
	const store09 = useStore($numberStore09, { ssr: 'initial' });
	const { $numberStore10 } = useReactStore('nanoNumber10');

	useLayoutEffect(() => {
		if (!store09) return;

		$numberStore09.set(store09 + 1);
		if (store09 === dragRaceMax) {
			$numberStore09.set(0);
			$numberStore10.set(1);
		}
	}, [ store09 ]);

	return null;
}

// src/components/features/Solid/dragRace/nano/number/Number09.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax } from "@/_global/lib/dragRace";

export default function NanoNumber09() {
	const { numberStore09 } = useNanoStore('nanoNumber09');
	const store = useStore(numberStore09);
	const { numberStore10 } = useNanoStore('nanoNumber10');

	createEffect(() => {
		if (!store()) return;

		numberStore09.set(store() + 1);
		if (store() === dragRaceMax) {
			numberStore09.set(0);
			numberStore10.set(1);
		}
	});

	return null;
}
