// src/components/features/Solid/performance04/_children/Child07.tsx
import { createMemo } from "solid-js";
import { logProps } from "@/_global/lib/performance04";
import { Child08 } from "./";
import type { RelayProps } from "../_models/relayContext";

export default function Child07(props: RelayProps) {
	const relayData = createMemo(() => {
		if (!props.relay) return 0;

		logProps();
		return props.relay;
	});

	return <Child08 relay={ relayData() } />;
};

// src/components/features/React/performance04/_children/Child07.tsx
/** @jsxImportSource react */

import { useMemo } from "react";
import { logProps } from "@/_global/lib/performance04";
import { Child08 } from "./";
import type { RelayProps } from "../_models/types";

export default function Child07(props: RelayProps) {
	const relayData = useMemo(() => {
		if (!props.relay) return 0;

		logProps();
		return props.relay;
	}, [ props.relay ]);

	return <Child08 relay={ relayData } />;
};
