// src/components/features/Vue/performance04/_models/RelayContext.vue
<script lang="ts">
	import { ref, defineComponent, provide, inject, readonly } from "vue";
	import { logContext } from "@/_global/lib/performance04";
	import type { InjectionKey, PropType, Ref } from "vue";

	type RelayData = number;
	const initialValue: RelayData = 0;
	type RelayDataRef = Ref<RelayData>;
	const RelayDataSymbol: InjectionKey<RelayDataRef> = Symbol();

	const provideRelayData = (value: RelayDataRef) => {
		provide(RelayDataSymbol, value);
	};

	export const useRelayDataContexts = () => {
		const injected = inject(RelayDataSymbol);
		if (!injected) {
			return {
				relayData: readonly({ value: initialValue }),
				setRelayData: (_: RelayData) => {},
				setRelayDataWithLog: (_: RelayData) => {},
			}
		};

		const relayData = readonly(injected);
		const setRelayData = (value: RelayData) => { injected.value = value; };
		const setRelayDataWithLog = (value: RelayData = 0) => {
			logContext();
			injected.value = value;
		};

		return { relayData, setRelayData, setRelayDataWithLog };
	};
	export type RelayProps = {
		relay: RelayData;
	};
	export default defineComponent({
		name: 'Relay',
		props: {
			relay: {
				type: Number as PropType<RelayData>,
				default: initialValue,
			},
		},
		setup(props) {
			provideRelayData(ref(props.relay));
		}
	});
</script>
<template>
	<slot />
</template>

// src/components/features/Solid/performance04/_models/relayContext.tsx
import { createContext, createSignal, useContext } from "solid-js";
import { logContext } from "@/_global/lib/performance04";
import type { Context, JSX } from "solid-js";

export type RelayData = number;
export type RelayProps = {
	relay: RelayData;
};

const createRelayDataContexts = () => {
	const [ relayData, setRelayData ] = createSignal<RelayData>(0);
	const setRelayDataWithLog = (value: RelayData = 0) => {
		logContext();
		setRelayData(value);
	};

	return { relayData, setRelayData, setRelayDataWithLog };
};
type RelayDataContextsType = ReturnType<typeof createRelayDataContexts>;
const RelayDataContexts = createContext<RelayDataContextsType>() as Context<RelayDataContextsType>;

export const RelayDataProvider = (props: { children: JSX.Element }) => {
	return (
		<RelayDataContexts.Provider value={ createRelayDataContexts() }>{ props.children }</RelayDataContexts.Provider>
	);
}
export const useRelayDataContexts = () => useContext(RelayDataContexts);
