// src/components/features/Solid/performance04/_children/Child00.tsx
import { createEffect, createSignal } from "solid-js";
import { useStore } from "@/_global/piquo";
import { recordStart, recordFinished } from "@/_global/lib/performance04";
import { useRelayDataContexts } from "../_models/relayContext";
import { Child01 } from "./";

export default function Child00() {
	const { relayData, setRelayData } = useRelayDataContexts();
	const { solidRaceId, solidSetRaceId } = useStore('solidRaceId');
	const [ relayStart, setRelayStart ] = createSignal(0);

	createEffect(() => {
		if (solidRaceId() !== 'Props' || relayData()) return;

		recordStart('Props');
		setRelayStart(1);
	});

	createEffect(() => {
		if (solidRaceId() !== 'Context' || !relayData()) return;

		recordFinished('Context');
		setRelayData(0);
		setRelayStart(0);

		solidSetRaceId('Memo');
	});

	return <Child01 relay={ relayStart() } />;
};

// src/components/features/Svelte/performance04/_children/Child00.svelte
<script lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart, recordFinished } from "@/_global/lib/performance04";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import { Child01 } from "./";

	const { relayData, setRelayData } = useRelayDataContexts();
	const { svelteRaceId, svelteSetRaceId } = useStore('svelteRaceId');
	let relayStart = $state(0);

	$effect(() => {
		if (svelteRaceId() !== 'Props' || relayData()) return;

		recordStart('Props');
		relayStart = 1;
	});

	$effect(() => {
		if (svelteRaceId() !== 'Context' || !relayData()) return;

		recordFinished('Context');
		setRelayData(0);
		relayStart = 0;

		svelteSetRaceId('Memo');
	});
</script>
<Child01 relay={ relayStart } />
