// src/components/features/Solid/performance04/_quantumStores/Quantum02.tsx
import { createEffect, createMemo } from "solid-js";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum02() {
	const { solidQuantum02, solidSetQuantum03 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum02()) return 0;

		logStore();
		return solidQuantum02();
	});

	createEffect(() => {
		if (!relayData()) return;

		solidSetQuantum03(relayData());
	});

	return null;
}

// src/components/features/React/performance04/_quantumStores/Quantum02.tsx
/** @jsxImportSource react */

import { useLayoutEffect, useMemo, useSyncExternalStore } from "react";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "../_models/stores";

export default function Quantum02() {
	const quantum02 = useStore('quantum02');
	const quantum03 = useStore('quantum03');
	const quantumStore = useSyncExternalStore(quantum02.subscribe, quantum02.getSnapshot, quantum02.getServerSnapshot);

	const relayData = useMemo(() => {
		if (!quantumStore) return 0;

		logStore();
		return quantumStore;
	}, [ quantumStore ]);

	useLayoutEffect(() => {
		if (!relayData) return;

		quantum03.setStore(relayData);
	}, [ relayData ]);

	return null;
}
