// src/components/features/Solid/performance04/_quantumStores/Quantum01.tsx
import { createEffect, createMemo } from "solid-js";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "@/_global/piquo";

export default function Quantum01() {
	const { solidQuantum01, solidSetQuantum02 } = useStore('solidQuantum');

	const relayData = createMemo(() => {
		if (!solidQuantum01()) return 0;

		logStore();
		return solidQuantum01();
	});

	createEffect(() => {
		if (!relayData()) return;

		solidSetQuantum02(relayData());
	});

	return null;
}

// src/components/features/React/performance04/_quantumStores/Quantum01.tsx
/** @jsxImportSource react */

import { useLayoutEffect, useMemo, useSyncExternalStore } from "react";
import { logStore } from "@/_global/lib/performance04";
import { useStore } from "../_models/stores";

export default function Quantum01() {
	const quantum01 = useStore('quantum01');
	const quantum02 = useStore('quantum02');
	const quantumStore = useSyncExternalStore(quantum01.subscribe, quantum01.getSnapshot, quantum01.getServerSnapshot);

	const relayData = useMemo(() => {
		if (!quantumStore) return 0;

		logStore();
		return quantumStore;
	}, [ quantumStore ]);

	useLayoutEffect(() => {
		if (!relayData) return;

		quantum02.setStore(relayData);
	}, [ relayData ]);

	return null;
}
