// src/components/features/Svelte/performance02/_children/Child00.svelte
<script lang="ts">
	import { recordStart } from "@/_global/lib/performance02";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import { useStore } from "@/_global/piquo";
	import { Child01 } from "./";

	const { setRelayData } = useRelayDataContexts();
	const { svelteSetRelay } = useStore('svelteRelay');
	let relayStart = $state(0);

	const handleClick = () => {
		const start = relayStart + 1;
		recordStart('RelayProps');
		relayStart++;

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		svelteSetRelay(start);
	};
</script>
<fieldset>
	<button onclick={ handleClick }>バケツリレー開始</button>
</fieldset>
<Child01 relay={ relayStart } />

// src/components/features/Solid/performance02/_children/Child00.tsx
import { recordStart } from "@/_global/lib/performance02";
import { useRelayDataContexts } from "../_models/relayContext";
import { useStore } from "@/_global/piquo";
import { Child01 } from "./";
import { createSignal } from "solid-js";

export default function Child00() {
	const { setRelayData } = useRelayDataContexts();
	const { solidSetRelay } = useStore('solidRelay');
	const [ relayStart, setRelayStart ] = createSignal(0);

	const handleClick = () => {
		const start = relayStart() + 1;
		recordStart('RelayProps');
		setRelayStart(start);

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		solidSetRelay(start);
	};

	return (
		<>
			<fieldset>
				<button onClick={ handleClick }>バケツリレー開始</button>
			</fieldset>
			<Child01 relay={ relayStart() } />
		</>
	)
};
