// src/components/features/React/performance02/_children/Child00.tsx
/** @jsxImportSource react */

import { useContext, useState } from "react";
import { recordStart } from "@/_global/lib/performance02";
import { RelayContext } from "../_models/relayContext";
import { useStore } from "../_models/stores";
import { Child01 } from "./";

export default function Child00() {
	const { setRelay } = useContext(RelayContext);
	const store = useStore('relay');
	const [ relayStart, setRelayStart ] = useState(0);

	const handleClick = () => {
		const start = relayStart + 1;
		recordStart('RelayProps');
		setRelayStart(start);

		recordStart('RelayContext');
		setRelay(start);

		recordStart('RelayStore');
		store.setStore(start);
	};

	return (
		<>
			<fieldset>
				<button onClick={ handleClick }>バケツリレー開始</button>
			</fieldset>
			<Child01 relay={ relayStart } />
		</>
	)
};

// src/components/features/Solid/performance02/_children/Child00.tsx
import { recordStart } from "@/_global/lib/performance02";
import { useRelayDataContexts } from "../_models/relayContext";
import { useStore } from "@/_global/piquo";
import { Child01 } from "./";
import { createSignal } from "solid-js";

export default function Child00() {
	const { setRelayData } = useRelayDataContexts();
	const { solidSetRelay } = useStore('solidRelay');
	const [ relayStart, setRelayStart ] = createSignal(0);

	const handleClick = () => {
		const start = relayStart() + 1;
		recordStart('RelayProps');
		setRelayStart(start);

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		solidSetRelay(start);
	};

	return (
		<>
			<fieldset>
				<button onClick={ handleClick }>バケツリレー開始</button>
			</fieldset>
			<Child01 relay={ relayStart() } />
		</>
	)
};
