// src/components/features/Vue/performance02/_children/Child00.vue
<script setup lang="ts">
	import { ref } from "vue";
	import { recordStart } from "@/_global/lib/performance02";
	import { useRelayDataContexts } from "../_models/RelayContext.vue";
	import { useStore } from "@/_global/piquo";
	import { Child01 } from "./index.ts";

	const { setRelayData } = useRelayDataContexts();
	const { vueSetRelay } = useStore('vueRelay');
	const relayStart = ref(0);

	const handleClick = async () => {
		const start = relayStart.value + 1;
		recordStart('RelayProps');
		relayStart.value = start;

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		vueSetRelay(start);
	};
</script>
<template>
	<fieldset>
		<button @click="handleClick">バケツリレー開始</button>
	</fieldset>
	<Child01 :relay="relayStart" />
</template>

// src/components/features/Svelte/performance02/_children/Child00.svelte
<script lang="ts">
	import { recordStart } from "@/_global/lib/performance02";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import { useStore } from "@/_global/piquo";
	import { Child01 } from "./";

	const { setRelayData } = useRelayDataContexts();
	const { svelteSetRelay } = useStore('svelteRelay');
	let relayStart = $state(0);

	const handleClick = () => {
		const start = relayStart + 1;
		recordStart('RelayProps');
		relayStart++;

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		svelteSetRelay(start);
	};
</script>
<fieldset>
	<button onclick={ handleClick }>バケツリレー開始</button>
</fieldset>
<Child01 relay={ relayStart } />
