// src/components/features/React/performance03/_children/Child00.tsx
/** @jsxImportSource react */

import { useContext, useEffect, useState, useSyncExternalStore } from "react";
import { recordFinished } from "@/_global/lib/performance03";
import { RelayContext } from "../_models/relayContext";
import { useStore } from "../_models/stores";
import { Child01 } from "./";
import type { RelayData } from "../_models/types";

export default function Child00() {
	const { relayContext } = useContext(RelayContext);
	const store = useStore('relay');
	const relayStore = useSyncExternalStore(store.subscribe, store.getSnapshot, store.getServerSnapshot);
	const [ relay, setRelay ] = useState<RelayData>(0);

	useEffect(() => {
		if (!relay) return;

		recordFinished('RelaySetter');
	}, [ relay ]);

	useEffect(() => {
		if (!relayContext) return;

		recordFinished('RelayContext');
	}, [ relayContext ]);

	useEffect(() => {
		if (!relayStore) return;

		recordFinished('RelayStore');
	}, [ relayStore ]);

	return <Child01 relay={ relay } setRelay={ setRelay } />;
};

// src/components/features/Solid/performance03/_children/Child00.tsx
import { createEffect, createSignal } from "solid-js";
import { recordFinished } from "@/_global/lib/performance03";
import { useRelayDataContexts } from "../_models/relayContext";
import { useStore } from "@/_global/piquo";
import { Child01 } from ".";
import type { RelayData } from "../_models/relayContext";

export default function Child00() {
	const { relayData } = useRelayDataContexts();
	const { solidRelay } = useStore('solidRelay');
	const  [ relay, setRelay ] = createSignal<RelayData>(0);

	createEffect(() => {
		if (!relay()) return;

		recordFinished('RelaySetter');
	});

	createEffect(() => {
		if (!relayData()) return;

		recordFinished('RelayContext');
	});

	createEffect(() => {
		if (!solidRelay()) return;

		recordFinished('RelayStore');
	});

	return <Child01 relay={ relay() } setRelay={ setRelay } />;
}
