// src/components/features/Vue/performance03/_children/Child00.vue
<script setup lang="ts">
	import { ref, watch } from "vue";
	import { recordFinished } from "@/_global/lib/performance03";
	import { useRelayDataContexts } from "../_models/RelayContext.vue";
	import { useStore } from "@/_global/piquo";
	import { Child01 } from "./index.ts";
	import type { RelayData, RelaySetter } from "../_models/types.ts";

	const { relayData } = useRelayDataContexts();
	const { vueRelay } = useStore('vueRelay');
	let relay = ref(0);
	const setRelay: RelaySetter = (value: RelayData) => { relay.value = value; };

	watch(
		() => relay.value,
		() => {
			if (!relay.value) return;

			recordFinished('RelaySetter');
		},
		{ immediate: true }
	);

	watch(
		() => relayData.value,
		() => {
			if (!relayData.value) return;

			recordFinished('RelayContext');
		},
		{ immediate: true }
	);

	watch(
		() => vueRelay(),
		() => {
			if (!vueRelay()) return;

			recordFinished('RelayStore');
		},
		{ immediate: true }
	);
</script>
<template>
	<Child01 :relay="relay" :set-relay="setRelay" />
</template>

// src/components/features/Solid/performance03/_children/Child00.tsx
import { createEffect, createSignal } from "solid-js";
import { recordFinished } from "@/_global/lib/performance03";
import { useRelayDataContexts } from "../_models/relayContext";
import { useStore } from "@/_global/piquo";
import { Child01 } from ".";
import type { RelayData } from "../_models/relayContext";

export default function Child00() {
	const { relayData } = useRelayDataContexts();
	const { solidRelay } = useStore('solidRelay');
	const  [ relay, setRelay ] = createSignal<RelayData>(0);

	createEffect(() => {
		if (!relay()) return;

		recordFinished('RelaySetter');
	});

	createEffect(() => {
		if (!relayData()) return;

		recordFinished('RelayContext');
	});

	createEffect(() => {
		if (!solidRelay()) return;

		recordFinished('RelayStore');
	});

	return <Child01 relay={ relay() } setRelay={ setRelay } />;
}
