// src/components/features/Solid/dragRace/nano/string/String10.tsx
import { createEffect } from "solid-js";
import { useStore } from "@nanostores/solid";
import { useNanoStore } from "../../_models/nano";
import { dragRaceMax, recordFinished, logTotal } from "@/_global/lib/dragRace";

export default function NanoString10() {
	const { stringStore10 } = useNanoStore('nanoString10');
	const store = useStore(stringStore10);
	const { startStore } = useNanoStore('nanoStart');

	createEffect(() => {
		const value = +store();
		if (!value) return;

		if (value === dragRaceMax) {
			recordFinished('SolidNanoString');
			logTotal('SolidNano');
			startStore.set(null);
			stringStore10.set('');
		} else {
			stringStore10.set((value + 1).toString());
		}
	});

	return null;
}

// src/components/features/Svelte/dragRace/nano/string/String10.svelte
<script lang="ts">
	import { useStore } from "@nanostores/svelte-runes";
	import { useNanoStore } from "../../_models/nano";
	import { dragRaceMax, recordFinished, logTotal } from "@/_global/lib/dragRace";

	const { stringStore10 } = useNanoStore('nanoString10');
	const store = useStore(stringStore10);
	const { startStore } = useNanoStore('nanoStart');

	$effect(() => {
		const value = +store.current;
		if (!value) return;

		if (value === dragRaceMax) {
			recordFinished('SvelteNanoString');
			logTotal('SvelteNano');
			startStore.set(null);
			stringStore10.set('');
		} else {
			stringStore10.set((value + 1).toString());
		}
	});
</script>
