// src/components/features/Svelte/performance04/_children/Child00.svelte
<script lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart, recordFinished } from "@/_global/lib/performance04";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import { Child01 } from "./";

	const { relayData, setRelayData } = useRelayDataContexts();
	const { svelteRaceId, svelteSetRaceId } = useStore('svelteRaceId');
	let relayStart = $state(0);

	$effect(() => {
		if (svelteRaceId() !== 'Props' || relayData()) return;

		recordStart('Props');
		relayStart = 1;
	});

	$effect(() => {
		if (svelteRaceId() !== 'Context' || !relayData()) return;

		recordFinished('Context');
		setRelayData(0);
		relayStart = 0;

		svelteSetRaceId('Memo');
	});
</script>
<Child01 relay={ relayStart } />

// src/components/features/Vue/performance04/_children/Child00.vue
<script setup lang="ts">
	import { ref, watchEffect } from "vue";
	import { useStore } from "@/_global/piquo";
	import { recordStart, recordFinished } from "@/_global/lib/performance04";
	import { useRelayDataContexts } from "../_models/RelayContext.vue";
	import { Child01 } from "./";

	const { relayData, setRelayData } = useRelayDataContexts();
	const { vueRaceId, vueSetRaceId } = useStore('vueRaceId');
	const relayStart = ref(0);

	watchEffect(() => {
		if (vueRaceId() !== 'Props' || relayData.value) return;

		recordStart('Props');
		relayStart.value = 1;
	}, { flush: 'pre' });

	watchEffect(() => {
		if (vueRaceId() !== 'Context' || !relayData.value) return;

		recordFinished('Context');
		setRelayData(0);
		relayStart.value = 0;

		vueSetRaceId('Memo');
	}, { flush: 'pre' });
</script>
<template>
	<Child01 :relay="relayStart" />
</template>
