// src/components/features/Svelte/performance01/At.svelte
<script lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart, recordFinished } from "@/_global/lib/performance01";

	type Props = {
		id: string;
	};
	const { id }: Props = $props();

	const { svelteAtId, svelteSetAtId } = useStore('svelteAtId');

	let el: HTMLSpanElement | undefined;

	$effect(() => {
		if (!el || id !== svelteAtId()) return;

		el.scrollIntoView({ behavior: 'smooth' });
		recordFinished('GlobalSignal');
		svelteSetAtId('');
		recordStart('Hydration');
	});
</script>
<span bind:this={ el } id={ `at_${id}` } class="invisible_target"></span>

// src/components/features/Solid/performance01/At.tsx
import { createEffect } from "solid-js";
import { useStore } from "@/_global/piquo";
import { recordFinished, recordStart } from "@/_global/lib/performance01";

type Props = {
	id: string;
};

export default function At(props: Props) {
	const { solidAtId, solidSetAtId } = useStore('solidAtId');

	let el: HTMLSpanElement | undefined;

	createEffect(() => {
		if (!el || props.id !== solidAtId()) return;

		el.scrollIntoView({ behavior: 'smooth' });
		recordFinished('GlobalSignal');
		solidSetAtId('');
		recordStart('Hydration');
	});

	return (
		<span ref={ el } id={ `at_${props.id}` } class="invisible_target" />
	)
}
