// src/components/features/Solid/performance03/_children/Child10.tsx
import { useStore } from "@/_global/piquo";
import { recordStart } from "@/_global/lib/performance03";
import { useRelayDataContexts } from "../_models/relayContext";
import type { RelayProps } from "../_models/types";

export default function Child10(props: RelayProps) {
	const { relayData, setRelayData } = useRelayDataContexts();
	const { solidSetRelay } = useStore('solidRelay');

	const handleChange = () => {
		const start = relayData() + 1;

		recordStart('RelaySetter');
		props.setRelay(start);

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		solidSetRelay(start);
	};

	return (
		<fieldset>
			<input type="number" value={ props.relay } onChange={ handleChange } />
		</fieldset>
	)
};

// src/components/features/Svelte/performance03/_children/Child10.svelte
<script lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart } from "@/_global/lib/performance03";
	import { useRelayDataContexts } from "../_models/RelayContext.svelte";
	import type { RelayProps } from "../_models/types";

	let { relay = $bindable(), setRelay }: RelayProps = $props();

	const { relayData, setRelayData } = useRelayDataContexts();
	const { svelteSetRelay } = useStore('svelteRelay');

	const handleChange = () => {
		const start = relayData() + 1;

		recordStart('RelaySetter');
		setRelay(start);

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		svelteSetRelay(start);
	};

	$effect(() => {
		if (!relay) return;

		recordStart('RelayBindable');
	});
</script>
<fieldset>
	<input type="number" onchange={ handleChange } bind:value={ relay }>
</fieldset>
