// src/components/features/React/performance03/_children/Child10.tsx
/** @jsxImportSource react */

import { useContext } from "react";
import { useStore } from "../_models/stores";
import { recordStart } from "@/_global/lib/performance03";
import { RelayContext } from "../_models/relayContext";
import type { RelayProps } from "../_models/types";

export default function Child10(props: RelayProps) {
	const { relayContext, setRelayContext } = useContext(RelayContext);
	const store = useStore('relay');

	const handleChange = () => {
		const start = relayContext + 1;

		recordStart('RelaySetter');
		props.setRelay(start);

		recordStart('RelayContext');
		setRelayContext(start);

		recordStart('RelayStore');
		store.setStore(start);
	};

	return (
		<fieldset>
			<input type="number" onChange={ handleChange } value={ props.relay } />
		</fieldset>
	);
};

// src/components/features/Vue/performance03/_children/Child10.vue
<script setup lang="ts">
	import { useStore } from "@/_global/piquo";
	import { recordStart } from "@/_global/lib/performance03";
	import { useRelayDataContexts } from "../_models/RelayContext.vue";
	import type { RelayProps } from "../_models/types.ts";

	const props = defineProps<RelayProps>();

	const { relayData, setRelayData } = useRelayDataContexts();
	const { vueSetRelay } = useStore('vueRelay');

	const handleChange = async () => {
		const start = relayData.value + 1;

		recordStart('RelaySetter');
		props.setRelay(start);

		recordStart('RelayContext');
		setRelayData(start);

		recordStart('RelayStore');
		vueSetRelay(start);
	};
</script>
<template>
	<fieldset>
		<input type="number" @change="handleChange" :value="props.relay">
	</fieldset>
</template>
