// src/components/features/Vue/performance03/_quantumContexts/Quantum10.vue
<script setup lang="ts">
	import { watch } from "vue";
	import { useQuantumDataContexts } from "../_models/QuantumContext.vue";
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { vueSetQuantumContextStart } = useStore('vueQuantum');
	const { setQuantumData01, quantumData10 } = useQuantumDataContexts();

	const incrementContext = (value: number) => {
		setQuantumData01(value + 1);
	};

	watch(
		() => quantumData10.value,
		() => {
			if (!quantumData10.value) return;

			if (quantumData10.value >= loopTotal) {
				recordFinished('QuantumContext');

				vueSetQuantumContextStart(0);
				return;
			}

			incrementContext(quantumData10.value);
		},
		{ immediate: true }
	);
</script>
<template>
	<!-- return null -->
</template>

// src/components/features/Svelte/performance03/_quantumContexts/Quantum10.svelte
<script lang="ts">
	import { useQuantumDataContexts } from "../_models/QuantumContext.svelte";
	import { loopTotal, recordFinished } from "@/_global/lib/performance03";
	import { useStore } from "@/_global/piquo";

	const { svelteSetQuantumContextStart } = useStore('svelteQuantum');
	const { setQuantumData01, quantumData10 } = useQuantumDataContexts();

	const incrementContext = (value: number) => {
		setQuantumData01(value + 1);
	};

	$effect(() => {
		if (!quantumData10()) return;

		if (quantumData10() >= loopTotal) {
			recordFinished('QuantumContext');

			svelteSetQuantumContextStart(0);
			return;
		}

		incrementContext(quantumData10());
	});
</script>
