// src/components/features/Vue/performance01/Pics.vue
<script setup lang="ts">
	import { onMounted, ref, useTemplateRef, watchEffect } from "vue";
	import { picKeys, recordStart, recordFinished } from "@/_global/lib/performance01";
	import { Pic } from "./";

	const text = ref('');
	const elParagraph = useTemplateRef('elParagraph');

	onMounted(() => {
		recordFinished('Hydration');
	});
	const handleChange = async (e: Event) => {
		if (!e.currentTarget || !(e.currentTarget instanceof HTMLInputElement)) return;

		recordStart('ReRender');
		text.value = e.currentTarget.value;
	};
	watchEffect(() => {
		if (elParagraph.value?.textContent !== text.value) return;

		recordFinished('ReRender');
	}, { flush: 'post' });
</script>
<template>
	<form id="pics">
		<fieldset>
			<input type="text" @change="handleChange" />
		</fieldset>
		<Pic v-for="key in picKeys" :key="key" :pic-key="key" />
		<fieldset>
			<p ref="elParagraph">{{ text }}</p>
		</fieldset>
	</form>
</template>

// src/components/features/Svelte/performance01/Pics.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { picKeys, recordStart, recordFinished } from "@/_global/lib/performance01";
	import { Pic } from "./";

	let text = $state('');
	let elParagraph: HTMLParagraphElement | undefined;

	onMount(() => {
		recordFinished('Hydration');
	});
	const handleChange = async (e: Event & { currentTarget: EventTarget & HTMLInputElement; }) => {
		recordStart('ReRender');
		text = e.currentTarget.value;
	};
	$effect(() => {
		if (elParagraph?.textContent !== text) return;

		recordFinished('ReRender');
	});
</script>
<form id="pics">
	<fieldset>
		<input type="text" onchange={ handleChange } />
	</fieldset>
	{#each picKeys as picKey (picKey)}
		<Pic picKey={ picKey } />
	{/each}
	<fieldset>
		<p bind:this={ elParagraph }>{ text }</p>
	</fieldset>
</form>
