// src/components/features/Solid/performance01/Pics.tsx
import { createEffect, createSignal, Index, onMount } from "solid-js";
import { picKeys, recordStart, recordFinished } from "@/_global/lib/performance01";
import { Pic } from "./";

export default function Pics() {
	const [ text, setText ] = createSignal('');

	let elParagraph: HTMLParagraphElement | undefined;

	onMount(() => {
		recordFinished('Hydration');
	});
	const handleChange = (e: Event & { currentTarget: HTMLInputElement; target: HTMLInputElement; }) => {
		recordStart('ReRender');
		setText(e.currentTarget.value);
	};
	createEffect(() => {
		if (elParagraph?.textContent !== text()) return;

		recordFinished('ReRender');
	});

	return (
		<form id="pics">
			<fieldset>
				<input type="text" onChange={ handleChange } />
			</fieldset>
			<Index each={ picKeys }>
				{picKey => (
					<Pic picKey={ picKey() } />
				)}
			</Index>
			<fieldset>
				<p ref={ elParagraph }>{ text() }</p>
			</fieldset>
		</form>
	)
}

// src/components/features/Svelte/performance01/Pics.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { picKeys, recordStart, recordFinished } from "@/_global/lib/performance01";
	import { Pic } from "./";

	let text = $state('');
	let elParagraph: HTMLParagraphElement | undefined;

	onMount(() => {
		recordFinished('Hydration');
	});
	const handleChange = async (e: Event & { currentTarget: EventTarget & HTMLInputElement; }) => {
		recordStart('ReRender');
		text = e.currentTarget.value;
	};
	$effect(() => {
		if (elParagraph?.textContent !== text) return;

		recordFinished('ReRender');
	});
</script>
<form id="pics">
	<fieldset>
		<input type="text" onchange={ handleChange } />
	</fieldset>
	{#each picKeys as picKey (picKey)}
		<Pic picKey={ picKey } />
	{/each}
	<fieldset>
		<p bind:this={ elParagraph }>{ text }</p>
	</fieldset>
</form>
