// src/components/features/Solid/performance01/Anchor.tsx
import { useStore } from "@/_global/piquo";
import { recordStart } from "@/_global/lib/performance01";
import type { JSX } from "solid-js/jsx-runtime";

type Props = {
	to: string;
	children: JSX.Element;
};

export default function Anchor(props: Props) {
	const { solidSetAtId } = useStore('solidAtId');

	const handleClick = () => {
		recordStart('GlobalSignal');
		solidSetAtId(props.to);
	};

	return (
		<button onClick={ handleClick }>
			{ props.children }
		</button>
	)
};

// src/components/features/React/performance01/Anchor.tsx
/** @jsxImportSource react */

import { recordStart } from "@/_global/lib/performance01";
import { useStore } from "./_models/stores";
import type { ReactNode } from "react";

type Props = {
	to: string;
	children: ReactNode;
};

export default function Anchor(props: Props) {
	const store = useStore('atId');

	const handleClick = () => {
		recordStart('GlobalSignal');
		store.setStore(props.to);
	};

	return (
		<button onClick={ handleClick }>
			{ props.children }
		</button>
	)
};
